name: Acquire activation file

on:
  push:
    branches:
      - testing-ci-cd

env: 
  NAME: ${{ github.event.repository.name }}

jobs:

  build:
    name: Build
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
        clean: false
        fetch-depth: 0

    - name: Prepare PATH
      run: |
        echo "$GITHUB_WORKSPACE/unity-version-manager/bin" >> $GITHUB_PATH
        chmod -R 755 $GITHUB_WORKSPACE/unity-version-manager
        echo $GITHUB_PATH

    - name: Install Unity
      run: |
        uvm install2 -v 2020.2.2f1 /Applications/UnityInstalls/2020.2.2f1
        sudo mkdir /Library/Application\ Support/Unity
        sudo chmod -R 777 /Library/Application\ Support/Unity
       
    - name: Select Unity Version
      run: |
        uvm use 2020.2.2f1

    
    - name: Unity Create Activation file
      run: |
        /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -createManualActivationFile -logfile

    - name: Print
      run: |
        ls $HOME
        ls .
        ls $GITHUB_WORKSPACE
    
    # Upload artifact (Unity_v20XX.X.XXXX.alf)
    - name: Expose as artifact
      uses: actions/upload-artifact@v1
      with:
        name: "license.alf"
        path: $HOME/Unity_v2020.2.2f1.alf
  

